import ProductImage1 from "@/assets/product-image-1.png";
import ProductImage2 from "@/assets/product-image-2.png";
import ProductImage3 from "@/assets/product-image-3.png";
import ProductImage4 from "@/assets/product-image-4.png";
import ProductImage5 from "@/assets/product-image-5.png";
import ProductImage6 from "@/assets/product-image-6.png";
import ProductImage7 from "@/assets/product-image-7.png";
import ProductImage8 from "@/assets/product-image-8.png";
import thumb1 from "@/assets/thumbnail-1.png";
import thumb2 from "@/assets/thumbnail-2.png";
import thumb3 from "@/assets/thumbnail-3.png";
import thumb4 from "@/assets/thumbnail-4.png";
import { ProductItemType } from "@/types/products-items-type";

export const items: ProductItemType[] = [
  {
    id: 1,
    image: ProductImage1,
    title: "Syltherine",
    description: "Stylish cafe chair",
    price: 2_500,
    priceBeforeDiscount: 3_500,
    newItem: false,
    thumbnail: [thumb1, thumb2, thumb3, thumb4],
  },
  {
    id: 2,
    image: ProductImage2,
    title: "Leviosa",
    description: "Stylish cafe chair",
    price: 2_500,
    priceBeforeDiscount: 2_500,
    newItem: false,
    thumbnail: [thumb1, thumb2, thumb3, thumb4],
  },
  {
    id: 3,
    image: ProductImage3,
    title: "Lolito",
    description: "Luxury big sofa",
    price: 7_000,
    priceBeforeDiscount: 14_000,
    newItem: false,
    thumbnail: [thumb1, thumb2, thumb3, thumb4],
  },
  {
    id: 4,
    image: ProductImage4,
    title: "Respira",
    description: "Outdoor bar table and stool",
    price: 5_000,
    priceBeforeDiscount: 5_000,
    newItem: true,
    thumbnail: [thumb1, thumb2, thumb3, thumb4],
  },
  {
    id: 5,
    image: ProductImage5,
    title: "Grifo",
    description: "Night lamp",
    price: 1_500,
    priceBeforeDiscount: 1_500,
    newItem: false,
    thumbnail: [thumb1, thumb2, thumb3, thumb4],
  },
  {
    id: 6,
    image: ProductImage6,
    title: "Muggo",
    description: "Small mug",
    price: 7_500,
    priceBeforeDiscount: 13_500,
    newItem: false,
    thumbnail: [thumb1, thumb2, thumb3, thumb4],
  },
  {
    id: 7,
    image: ProductImage7,
    title: "Pingky",
    description: "Cute bed set",
    price: 9_500,
    priceBeforeDiscount: 17_300,
    newItem: false,
    thumbnail: [thumb1, thumb2, thumb3, thumb4],
  },
  {
    id: 8,
    image: ProductImage8,
    title: "Potty",
    description: "Minimalist flower pot",
    price: 5_000,
    priceBeforeDiscount: 5_000,
    newItem: true,
    thumbnail: [thumb1, thumb2, thumb3, thumb4],
  },
  {
    id: 9,
    image: ProductImage6,
    title: "Muggo",
    description: "Small mug",
    price: 7_500,
    priceBeforeDiscount: 13_500,
    newItem: false,
    thumbnail: [thumb1, thumb2, thumb3, thumb4],
  },
  {
    id: 10,
    image: ProductImage7,
    title: "Pingky",
    description: "Cute bed set",
    price: 9_500,
    priceBeforeDiscount: 17_300,
    newItem: false,
    thumbnail: [thumb1, thumb2, thumb3, thumb4],
  },
  {
    id: 11,
    image: ProductImage4,
    title: "Respira",
    description: "Outdoor bar table and stool",
    price: 5_000,
    priceBeforeDiscount: 5_000,
    newItem: true,
    thumbnail: [thumb1, thumb2, thumb3, thumb4],
  },
  {
    id: 12,
    image: ProductImage3,
    title: "Lolito",
    description: "Luxury big sofa",
    subdescription:
      "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.",
    price: 7_000,
    priceBeforeDiscount: 14_000,
    newItem: false,
    thumbnail: [thumb1, thumb2, thumb3, thumb4],
  },
  {
    id: 13,
    image: ProductImage4,
    title: "Respira",
    description: "Outdoor bar table and stool",
    price: 5_000,
    priceBeforeDiscount: 5_000,
    newItem: true,
    thumbnail: [thumb1, thumb2, thumb3, thumb4],
  },
  {
    id: 14,
    image: ProductImage1,
    title: "Syltherine",
    description: "Stylish cafe chair",
    price: 2_500,
    priceBeforeDiscount: 3_500,
    newItem: false,
    thumbnail: [thumb1, thumb2, thumb3, thumb4],
  },
  {
    id: 15,
    image: ProductImage7,
    title: "Pingky",
    description: "Cute bed set",
    price: 9_500,
    priceBeforeDiscount: 17_300,
    newItem: false,
    thumbnail: [thumb1, thumb2, thumb3, thumb4],
  },
  {
    id: 16,
    image: ProductImage4,
    title: "Respira",
    description: "Outdoor bar table and stool",
    price: 5_000,
    priceBeforeDiscount: 5_000,
    newItem: true,
    thumbnail: [thumb1, thumb2, thumb3, thumb4],
  },
];
